#!/bin/bash

################################################################################
# CLEAN UP TEMPORARY WORKFLOW DIRECTORIES GENERATED BY SINGULARITIES
#
################################################################################

# usage documentation - shown if no PATH.txt file is found
Usage() {
    echo
	echo
    echo "Usage:"
    echo "./clean_environment.sh"
    echo
	echo
	echo "This script will look for a PATHS.txt file saved 2 directories above where this script is saved"
	echo
	echo
    echo "Script created by Melissa Thye"
    echo
    exit
}

if [ ! -f ../../PATHS.txt ]
then Usage
fi

# define directories
projDir=`cat ../../PATHS.txt`
singularityDir="${projDir}/singularity_images"

# display subjects
echo
echo "Cleaning up temporary workflow directories in..." ${singularityDir}
echo

# remove temporary directories
rm -r --interactive=never ${singularityDir}/fmriprep-23_2_wf
rm -r --interactive=never ${singularityDir}/rootfs*
rm -r --interactive=never ${singularityDir}/20*
rm -r ${singularityDir}/fmriprep
rm -r --interactive=never ${singularityDir}/*_sandbox