#!/bin/bash

################################################################################
# CLEAN UP TEMPORARY WORKFLOW DIRECTORIES GENERATED BY SINGULARITIES
#
################################################################################

# usage documentation - shown if no PATH.txt file is found
Usage() {
	echo
	echo
	echo "Usage:"
	echo "./clean_environment.sh"
	echo
	echo
	echo "This script will look for a PATHS.txt file saved 2 directories above where this script is saved"
	echo
	echo
	echo "Script created by Melissa Thye"
	echo
	exit
}

if [ ! -f ../../PATHS.txt ]
	then Usage
fi

# define directories
projDir=`cat ../../PATHS.txt`
singularityDir="${projDir}/singularity_images"

# display subjects
echo
echo "Cleaning up temporary workflow directories in..." ${singularityDir}
echo

# remove temporary files and directories leaving only singularity images
find ${singularityDir}/. -type f ! -iname "*.simg" -delete
rm -rf -- ${singularityDir}/./*/

# search for any analysis processing directories to clean up
for dir in $(ls -d ${projDir}/analysis/*/*/)
do
	if [ -d ${dir%/}/processing ]
	then
		echo
		echo "Cleaning up temporary analysis processing directories in..." ${dir%/}
		echo
		
		rm -r ${dir%/}/processing
	fi

done